### ISSUE TITLE
Unable to install through AUR

### ISSUE THREAD

**Issue by ghost** [memeplex/maximal#4]
I'm getting the below error when I try to install on arch.

_Preparing..._
_Cloning maximal build files..._
_Checking maximal dependencies..._

_Building maximal..._
_==> Making package: maximal 20180705-1 (Sun 04 Nov 2018 01:02:46 AM PST)_
_==> Checking runtime dependencies..._
_==> Checking buildtime dependencies..._
_==> Retrieving sources..._
_-> Cloning maximal git repo..._
_fatal: destination path '/var/tmp/pamac-build-navtoj/maximal/maximal' already exists and is not an empty_ _directory._
_==> ERROR: Failure while downloading maximal git repo_
_Aborting..._

I've tried installing after clearing the temp directory but still get the same error.

**Comment by memeplex** [comment]
Apparently this was fixed in https://github.com/memeplex/maximal/pull/2 but not pushed to the AUR yet. You might try cloning this repo and building directly from the PKGBUILD  with makepkg.

Btw, I'm not maintaining this anymore, but @crazygolem  might be taking ownership in the near future (see the discussion at https://github.com/memeplex/maximal/pull/3).

**Comment by memeplex** [comment]
Please report to https://github.com/crazygolem/maximal
